### ISSUE TITLE
pythia.voronoi no longer works

### ISSUE THREAD

**Issue by rosecers** [glotzerlab/pythia#12]
voronoi.angle_histogram(box=frame.box, positions=frame.positions, bins=range(180))

/usr/lib/python3.7/site-packages/pythia/voronoi.py in angle_histogram(box, positions, bins, buffer_distance, area_weight_mode)
     73 
     74     fbox = freud.box.Box.from_box(box)
---> 75     voronoi = freud.voronoi.Voronoi(fbox, buff=buffer_distance)
     76     voronoi.compute(positions)
     77 

AttributeError: module 'freud' has no attribute 'voronoi'

**Comment by bdice** [comment]
@rosecers I see you closed this issue right after creating it, so maybe you've already resolved it. If not, there may be a mismatch between freud and pythia. freud v2 uses a different API. In #11, I updated the modules to the new freud syntax. However, this version of pythia hasn't been released yet. If you use `master`, pythia will work with freud v2. Otherwise, you will need to use freud v1 with pythia v0.2.5 (the current release).
